global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']

  - job_name: 'otel_collector'
    static_configs:
      - targets: ['otel-collector:9464']